# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIbtIyB4lMawHFRflpdLJ5z9DjiW8DpS

## Pandasa giriş
"""

import pandas as pd
import numpy as np

#seriler tek boyutludur
s = pd.Series([10,20,30,40],index = ["a","b","c","d"])
s

# dataframe iki boyutludur
data = {
    "isim": ["ali","ayşe","mehmet"],
    "yas": [25,30,22],
    "sehir": ["istanbul","ankara","izmir"]
}
df = pd.DataFrame(data)
df

print(f"Şekil (satır,sütün): {df.shape}")
print(f"Sütün isimleri: {df.columns}")
print(f"İndeksler: {df.index}")
print(f"veri tipi: {df.dtypes}")

"""## Pandas Seriler"""

s1 = pd.Series([10,20,30,40]) #listeden seri oluşturma
s1

s2 = pd.Series([10,20,30,40],index=["a","b","c","d"])
s2

data = {"Ali": 55, "Ayşe":45, "Mehmet":25}
s3 = pd.Series(data)
s3

s = pd.Series([10,20,30,40],index=["a","b","c","d"])
print(f"Değerler: {s.values}")
print(f"İndeksler: {s.index}")
print(f"Veri Tipi: {s.dtype}")
print(f"Boyut: {s.shape}")

print(s["b"])
print(s["a":"c"])
print(s[0:2])

print(f"Toplam: {s.sum()}")

s = pd.Series([10,20,30,30,30,50,50])
print(s.unique())
print(s.value_counts())

"""## Pandas Dataframe"""

data = {
    "isim": ["Ali","Ayşe","Mehmet"],
    "yas": [25,30,22],
    "sehir": ["İstanbul","Ankara","İzmir"]
}
df = pd.DataFrame(data)
df

arr = np.array([[1,"Ali",25],[2,"Ayşe",30],[3,"Mehmet",22]])
df = pd.DataFrame(arr,columns=["id","isim","yas"])
df

# satır ve sütün seçimleri

print(df["yas"])
print(df.loc[:,"yas"])

print(df[["isim","yas"]])
print(df.loc[:,["isim","yas"]])

#sütün ekleme ve sütün silme
df["puan"] = [80,90,85]
df

df.drop("yas",axis=1,inplace=True) #axis = 1 -> sütün sil demek
df

"""## Veri Kaydetme ve Okuma"""

data = {
    "isim": ["Ali","Ayşe","Mehmet"],
    "yas": [25,30,22],
    "sehir": ["İstanbul","Ankara","İzmir"]
}
df = pd.DataFrame(data)
# kaydet
df.to_csv("ogrenciler.csv",index=False)
df.to_excel("ogrenciler.xlsx",index=False)
df.to_json("ogrenciler.json",orient="records",lines=True)

#tekrar oku
df1 = pd.read_csv("ogrenciler.csv")
df2 = pd.read_excel("ogrenciler.xlsx")
df3 = pd.read_json("ogrenciler.json",lines=True)

"""## Veri inceleme ve özetleme"""

# ilk ve son satırlara bakmak
data = {
    "isim":["ali","ayşe","mehmet","zeynep","burak"],
    "yas":[25,30,22,28,27],
    "not":[80,90,75,95,85]
}
df = pd.DataFrame(data)
print(df.head(3)) #ilk x satır
print(df.tail(3)) #son x satır

# genel bilgiler
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())

#temel istatiksel analiz
print(df.describe())

print(df.isnull()) #eksik değer var mı
print(df.isnull().sum()) #her sütundaki eksik değer sayısı

df.loc[2,"not"] = None
print(df.isnull())
print(df.isnull().sum())

#benzersiz değerler
print(df["yas"].unique())
print(df["yas"].nunique())
print(df.value_counts())

df["yas"].value_counts()