# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIbtIyB4lMawHFRflpdLJ5z9DjiW8DpS

## Pandasa giriş
"""

import pandas as pd
import numpy as np

#seriler tek boyutludur
s = pd.Series([10,20,30,40],index = ["a","b","c","d"])
s

# dataframe iki boyutludur
data = {
    "isim": ["ali","ayşe","mehmet"],
    "yas": [25,30,22],
    "sehir": ["istanbul","ankara","izmir"]
}
df = pd.DataFrame(data)
df

print(f"Şekil (satır,sütün): {df.shape}")
print(f"Sütün isimleri: {df.columns}")
print(f"İndeksler: {df.index}")
print(f"veri tipi: {df.dtypes}")

"""## Pandas Seriler"""

s1 = pd.Series([10,20,30,40]) #listeden seri oluşturma
s1

s2 = pd.Series([10,20,30,40],index=["a","b","c","d"])
s2

data = {"Ali": 55, "Ayşe":45, "Mehmet":25}
s3 = pd.Series(data)
s3

s = pd.Series([10,20,30,40],index=["a","b","c","d"])
print(f"Değerler: {s.values}")
print(f"İndeksler: {s.index}")
print(f"Veri Tipi: {s.dtype}")
print(f"Boyut: {s.shape}")

print(s["b"])
print(s["a":"c"])
print(s[0:2])

print(f"Toplam: {s.sum()}")

s = pd.Series([10,20,30,30,30,50,50])
print(s.unique())
print(s.value_counts())

"""## Pandas Dataframe"""

data = {
    "isim": ["Ali","Ayşe","Mehmet"],
    "yas": [25,30,22],
    "sehir": ["İstanbul","Ankara","İzmir"]
}
df = pd.DataFrame(data)
df

arr = np.array([[1,"Ali",25],[2,"Ayşe",30],[3,"Mehmet",22]])
df = pd.DataFrame(arr,columns=["id","isim","yas"])
df

# satır ve sütün seçimleri

print(df["yas"])
print(df.loc[:,"yas"])

print(df[["isim","yas"]])
print(df.loc[:,["isim","yas"]])

#sütün ekleme ve sütün silme
df["puan"] = [80,90,85]
df

df.drop("yas",axis=1,inplace=True) #axis = 1 -> sütün sil demek
df

"""## Veri Kaydetme ve Okuma"""

data = {
    "isim": ["Ali","Ayşe","Mehmet"],
    "yas": [25,30,22],
    "sehir": ["İstanbul","Ankara","İzmir"]
}
df = pd.DataFrame(data)
# kaydet
df.to_csv("ogrenciler.csv",index=False)
df.to_excel("ogrenciler.xlsx",index=False)
df.to_json("ogrenciler.json",orient="records",lines=True)

#tekrar oku
df1 = pd.read_csv("ogrenciler.csv")
df2 = pd.read_excel("ogrenciler.xlsx")
df3 = pd.read_json("ogrenciler.json",lines=True)

"""## Veri inceleme ve özetleme"""

# ilk ve son satırlara bakmak
data = {
    "isim":["ali","ayşe","mehmet","zeynep","burak"],
    "yas":[25,30,22,28,27],
    "not":[80,90,75,95,85]
}
df = pd.DataFrame(data)
print(df.head(3)) #ilk x satır
print(df.tail(3)) #son x satır

# genel bilgiler
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())

#temel istatiksel analiz
print(df.describe())

print(df.isnull()) #eksik değer var mı
print(df.isnull().sum()) #her sütundaki eksik değer sayısı

df.loc[2,"not"] = None
print(df.isnull())
print(df.isnull().sum())

#benzersiz değerler
print(df["yas"].unique())
print(df["yas"].nunique())
print(df.value_counts())

df["yas"].value_counts()

"""## Veri Seçme ve Filtreleme"""

data = {
    "isim":["ali","ayşe","mehmet","zeynep","burak"],
    "yas":[25,30,22,28,27],
    "not":[80,90,75,95,85]
}
df = pd.DataFrame(data)
print(f"Notu 85 den büyük olanlar: \n {df[df["not"] > 85]}")
print(f"Yaşı 25 olanlar: \n {df[df["yas"] == 25]}")

#boolean maskeler
mask = df["not"] > 85
df[mask]

#çoklu koşullar
# 50 <= not <= 90
print(f"Orta başarı: \n {df[(df["not"] >= 50) & (df["not"] <= 90)]}")

"""## Veri Temizleme"""

data = {
    "isim":["ali","ayşe","mehmet","zeynep","burak"],
    "yas":[25,None,22,None,27],
    "not":[80,90,None,95,85]
}
df = pd.DataFrame(data)
df.isnull()

df.dropna() #silme

df.fillna(0) #eksik veri doldurma

df["yas"].fillna(df["yas"].mean())

#yinelenen veriler
data = {
    "isim":["ali","ayşe","ali","zeynep","burak"],
    "yas":[25,None,25,None,27],
    "not":[80,90,80,None,85]
}
df = pd.DataFrame(data)
df.duplicated() #yinelenen değer kontrolu, satır satır bakıyor yani her şeyi aynı mı diye

df.drop_duplicates()

#değer değiştirme
df.replace({"ali":"ali_isim"})

data = {
    "isim":[" ali","Ayse","mehmet","zeYnep","burak"],
    "yas":[25,21,22,23,27],
    "not":[80,90,75,95,85]
}
df = pd.DataFrame(data)
df["isim"] = df["isim"].str.lower() #küçük harf yap
df["isim"] = df["isim"].str.strip() #boşluktan kurtul
df

"""## Veri Dönüştürme"""

data = {
    "isim":["ali","ayşe","mehmet","zeynep","burak"],
    "yas":[25,30,22,28,27],
    "not":[80,90,75,95,85]
}
df = pd.DataFrame(data)
df = df.sort_values(by = "not",ascending = False) #notlara göre sıralama

#yeniden indeksleme
df = df.reindex([0,1,2,3,4])
df

#tip dönüştürme
df.info()
df["not"] = df["not"].astype(float)
df["yas"] = df["yas"].astype(str)
df

#kategorik veri ekle
df["sehir"] = ["ankara","izmir","antalya","konya","istanbul"]
df["sehir"] = df["sehir"].astype("category")
df.info()

"""## Gruplama ve Özetleme"""

#temel gruplama
data = {
    "departman": ["IT","IT","HR","HR","Muhasebe","IT"],
    "personel" : ["ali","ayşe","mehmet","zeynep","burak","can"],
    "maaş" : [1222,1333,1444,1414,8666,1279]
    }
df = pd.DataFrame(data)
df.groupby("departman")["maaş"].mean()

#toplama, ortalama ve sayma
df.groupby("departman")["maaş"].sum() #toplam maaş

df.groupby("departman")["maaş"].count() #kişi sayısı

# birden fazla sütuna göre gruplama
data = {
    "departman": ["IT","IT","HR","HR","Muhasebe","IT"],
    "personel" : ["ali","ayşe","mehmet","zeynep","burak","can"],
    "sehir" : ["Ankara","İstanbul","Rize","Rize","İstanbul","Rize"],
    "maaş" : [1222,1333,1444,1414,8666,1279]
    }
df = pd.DataFrame(data)
df.groupby(["departman","sehir"])["maaş"].mean()

#agg()
df.groupby("departman")["maaş"].agg(["min","max","mean"])

"""## Birleştirme ve Bir Araya Getirme"""

#merge
df1 = pd.DataFrame({"id":[1,2,3],"isim":["Ali","Ayşe","Mehmet"]})
df2 = pd.DataFrame({"id":[1,2,4],"şehir":["Ankara","İstanbul","İzmir"]})
df_merge = pd.merge(df1,df2,on="id",how="inner") #ortak olan kayıtlar
df_merge

df_merge = pd.merge(df1,df2,on="id",how="left") #soldaki veriseti için tüm kayıtlar
df_merge

df_merge = pd.merge(df1,df2,on="id",how="right") #sağdaki veriseti için tüm kayıtlar
df_merge

#indeks bazlı birleştirme
df1 = pd.DataFrame({"isim":["Ali","Ayşe","Mehmet"]},index=["a","b","c"])
df2 = pd.DataFrame({"not": [85,90,75]},index=["a","b","d"])

pd.merge(df1,df2,left_index=True,right_index=True,how="outer") # her iki tarafın tüm kayıtları gelir