# -*- coding: utf-8 -*-
"""pandas_numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z-KZkVDFyfPQ28Nvvr9QzPG75H-QfHaF
"""

import numpy as np

print(f"Aralık ile array tanımla: \n {np.arange(0,10,2)}") #ilk eleman dahil, son eleman dahil değil

print(f"Eşit aralıklar ile array: \n {np.linspace(0,9,6)}") #ilk ve son eleman dahil